### ISSUE TITLE
Update Nino's discord invite link as it doesn't works since a long ago

### ISSUE THREAD

**Issue by simonetx** [uSebazz/Nino#62]
;)

**Comment by simonetx** [comment]
@hyduez can u send me the nino's discord server pls¿  

DC: brxnn#9649

**Comment by hyduez** [comment]
> @hyduez can u send me the nino's discord server pls¿
> 
> DC: brxnn#9649

[click here](https://discord.gg/ybYRJygm6t)

**Comment by uSebazz** [comment]
done
